### ISSUE TITLE
Limit of 100 branches

### ISSUE THREAD

**Issue by escudero89** [Balvajs/delete-stale-branches#182]
The limit of branches is 100: https://github.com/Balvajs/delete-stale-branches/blob/main/src/get-branches.ts#L9

So, if the repo has more than 100 branches, the stale ones won't get deleted completely.

On our team repo, we have more than 100 branches (closer to 400), so this action is not that useful until that is tackled.

**Comment by escudero89** [comment]
Ah no, the problem I was seeing is that we don't close stale branch without associated PRs. This issue is wrong.

**Comment by Balvajs** [comment]
Yes, for closing stale PRs there is [official GH action](https://github.com/actions/stale), so I didn't find it necessary to extend my action with the option to delete stale PRs.
