### ISSUE TITLE
Add parameter in the Octokit initialization to support GHES

### ISSUE THREAD

**Issue by Sorana-Maria** [Balvajs/delete-stale-branches#194]
Hi! We would like to make use of this action, but it won't work with the GitHub enterprise server version:
This initiates an octokit client with the given token. [refer here](https://github.com/Balvajs/delete-stale-branches/blob/main/src/get-octokit.ts#L5)
Octokit is from the [@octokit/core](https://www.npmjs.com/package/@octokit/core) and it needs an additional parameter [options.baseUrl] in the Octokit initialization to support the GHES.
Could it be added? Thank you!

**Comment by Balvajs** [comment]
Yes, sure, that makes total sense.
I don't have experience with GHES, and I wonder if I can get that URL from the GHA context `github.server_url`, or if it has to be action input. @Sorana-Maria is it possible to get the GHES URL from [`github.server_url`](https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/contexts#github-context) in your use case? If yes, I could do that internally without adding another user input.

<img width="668" alt="image" src="https://github.com/Balvajs/delete-stale-branches/assets/16807011/d42548f3-7adc-4af3-ad19-3a8289c21d66">

**Comment by Balvajs** [comment]
Or maybe it's solved by [@octokit/action](https://www.npmjs.com/package/@octokit/action) out of the box, isn't it? I don't know why I am not using that lib instead 😅

**Comment by Balvajs** [comment]
There is a new release now https://github.com/Balvajs/delete-stale-branches/releases/tag/v2.1.0, check it out, it should make this work for you 🚀
